pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'NeoForged Releases'
            url = 'https://maven.neoforged.net/releases'
        }
    }
}

plugins {
    // 允许 Gradle 在缺少 JDK 21 时自动下载工具链（纯离线环境可注释掉这一行）
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'playersuite'
